'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DictService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://services.aonaware.com/webservices/", ConfigurationName:="DictService.DictServiceSoap")>  _
    Public Interface DictServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.aonaware.com/webservices/ServerInfo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ServerInfo() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.aonaware.com/webservices/DictionaryList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DictionaryList() As DictService.Dictionary()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.aonaware.com/webservices/DictionaryListExtended", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DictionaryListExtended() As DictService.Dictionary()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.aonaware.com/webservices/DictionaryInfo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DictionaryInfo(ByVal dictId As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.aonaware.com/webservices/Define", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function Define(ByVal word As String) As DictService.WordDefinition
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.aonaware.com/webservices/DefineInDict", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function DefineInDict(ByVal dictId As String, ByVal word As String) As DictService.WordDefinition
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.aonaware.com/webservices/StrategyList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function StrategyList() As DictService.Strategy()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.aonaware.com/webservices/Match", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function Match(ByVal word As String, ByVal strategy As String) As DictService.DictionaryWord()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.aonaware.com/webservices/MatchInDict", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function MatchInDict(ByVal dictId As String, ByVal word As String, ByVal strategy As String) As DictService.DictionaryWord()
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.aonaware.com/webservices/")>  _
    Partial Public Class Dictionary
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private nameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.aonaware.com/webservices/")>  _
    Partial Public Class DictionaryWord
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dictionaryIdField As String
        
        Private wordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property DictionaryId() As String
            Get
                Return Me.dictionaryIdField
            End Get
            Set
                Me.dictionaryIdField = value
                Me.RaisePropertyChanged("DictionaryId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Word() As String
            Get
                Return Me.wordField
            End Get
            Set
                Me.wordField = value
                Me.RaisePropertyChanged("Word")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.aonaware.com/webservices/")>  _
    Partial Public Class Strategy
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("Description")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.aonaware.com/webservices/")>  _
    Partial Public Class Definition
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private wordField As String
        
        Private dictionaryField As Dictionary
        
        Private wordDefinitionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Word() As String
            Get
                Return Me.wordField
            End Get
            Set
                Me.wordField = value
                Me.RaisePropertyChanged("Word")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Dictionary() As Dictionary
            Get
                Return Me.dictionaryField
            End Get
            Set
                Me.dictionaryField = value
                Me.RaisePropertyChanged("Dictionary")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property WordDefinition() As String
            Get
                Return Me.wordDefinitionField
            End Get
            Set
                Me.wordDefinitionField = value
                Me.RaisePropertyChanged("WordDefinition")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.aonaware.com/webservices/")>  _
    Partial Public Class WordDefinition
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private wordField As String
        
        Private definitionsField() As Definition
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Word() As String
            Get
                Return Me.wordField
            End Get
            Set
                Me.wordField = value
                Me.RaisePropertyChanged("Word")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=1)>  _
        Public Property Definitions() As Definition()
            Get
                Return Me.definitionsField
            End Get
            Set
                Me.definitionsField = value
                Me.RaisePropertyChanged("Definitions")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DictServiceSoapChannel
        Inherits DictService.DictServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DictServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of DictService.DictServiceSoap)
        Implements DictService.DictServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ServerInfo() As String Implements DictService.DictServiceSoap.ServerInfo
            Return MyBase.Channel.ServerInfo
        End Function
        
        Public Function DictionaryList() As DictService.Dictionary() Implements DictService.DictServiceSoap.DictionaryList
            Return MyBase.Channel.DictionaryList
        End Function
        
        Public Function DictionaryListExtended() As DictService.Dictionary() Implements DictService.DictServiceSoap.DictionaryListExtended
            Return MyBase.Channel.DictionaryListExtended
        End Function
        
        Public Function DictionaryInfo(ByVal dictId As String) As String Implements DictService.DictServiceSoap.DictionaryInfo
            Return MyBase.Channel.DictionaryInfo(dictId)
        End Function
        
        Public Function Define(ByVal word As String) As DictService.WordDefinition Implements DictService.DictServiceSoap.Define
            Return MyBase.Channel.Define(word)
        End Function
        
        Public Function DefineInDict(ByVal dictId As String, ByVal word As String) As DictService.WordDefinition Implements DictService.DictServiceSoap.DefineInDict
            Return MyBase.Channel.DefineInDict(dictId, word)
        End Function
        
        Public Function StrategyList() As DictService.Strategy() Implements DictService.DictServiceSoap.StrategyList
            Return MyBase.Channel.StrategyList
        End Function
        
        Public Function Match(ByVal word As String, ByVal strategy As String) As DictService.DictionaryWord() Implements DictService.DictServiceSoap.Match
            Return MyBase.Channel.Match(word, strategy)
        End Function
        
        Public Function MatchInDict(ByVal dictId As String, ByVal word As String, ByVal strategy As String) As DictService.DictionaryWord() Implements DictService.DictServiceSoap.MatchInDict
            Return MyBase.Channel.MatchInDict(dictId, word, strategy)
        End Function
    End Class
End Namespace
